export const ON_PLAY_WORKER_START = "ON_PLAY_WORKER_START";
export const ON_PLAY_WORKER_END_SUCCESS = "ON_PLAY_WORKER_END_SUCCESS";
export const ON_PLAY_WORKER_END_ERROR = "ON_PLAY_WORKER_END_ERROR";

export const ON_STOP_WORKER_START = "ON_STOP_WORKER_START";
export const ON_STOP_WORKER_END_SUCCESS = "ON_STOP_WORKER_END_SUCCESS";
export const ON_STOP_WORKER_END_ERROR = "ON_STOP_WORKER_END_ERROR";

export const ON_REMOVE_WORKER_START = "ON_REMOVE_WORKER_START";
export const ON_REMOVE_WORKER_END_SUCCESS = "ON_REMOVE_WORKER_END_SUCCESS";
export const ON_REMOVE_WORKER_END_ERROR = "ON_REMOVE_WORKER_END_ERROR";
